### PR TITLE
ApplyMixin

### PR DESCRIPTION
**Pull request by sergiodxa**

### CODE REVIEW

**Comment by sergiodxa** [comment]
I used `Object.assign`, a new feature of ES6 that Babel doesn't transpile, so if the plan is support old browsers (and IE) it will be necessary to load a polyfill like [https://www.npmjs.com/package/object-assign](https://www.npmjs.com/package/object-assign), I can added it to the package.json and send another commit.

**Comment by goncalvesjoao** [comment]
Nice catch man.
I actually thought that babel would take care of that, thanks for the heads up @sergiodxa!

I'm trying to avoid extra dependencies for such a small project like this one.
I believe sometime in the future that will be hard but for now we can avoid the need of Object.assign with a small change:

``` javascript
function applyMixin(targetClass, mixin) {
  // apply mixin to the target class
  // and return the mixed class
  Object.keys(mixin).forEach((key) => {
    // if the target class has the prop or method
    if (targetClass[key] || targetClass.prototype[key]) {
      // return it untouched
      return targetClass;
    }

    // get the value
    const value = mixin[key];

    // if the value is a functoin
    if (typeof value === 'function') {
      // add the value to the prototype
      // of the targetClass
      targetClass.prototype[key] = value;
      // return the target class
      return targetClass;
    }

    // add the value as a static prop
    targetClass[key] = value;
  });

  return targetClass;
}

function applyMixinBuilder(...mixins) {
  return (target) => {
    mixins.forEach((mixin) => applyMixin(target, mixin));

    return target;
  };
}

export default applyMixinBuilder;
```

what do you say Sergio.

**Comment by sergiodxa** [comment]
I like the idea of avoid using `Object.assign` so is not necessary a polyfill (I also don't like polyfills), but I like more a pure functional approach using `Array.prototype.reduce` instead of 2 `Array.prototype.forEach`.

``` javascript
function applyMixin(target, mixin) {
  // apply mixin to the target class
  // and return the mixed class
  return Object.keys(mixin).reduce((targetClass, key) => {
    // if the target class has the prop or method
    if (targetClass[key] || targetClass.prototype[key]) {
      // return it untouched
      return targetClass;
    }

    // get the value
    const value = mixin[key];

    // if the value is a functoin
    if (typeof value === 'function') {
      // add the value to the prototype
      // of the targetClass
      targetClass.prototype[key] = value;
      // return the target class
      return targetClass;
    }

    // add the value as a static prop
    targetClass[key] = value;

    // return the class
    return targetClass;
  }, target);
}

function applyMixinBuilder(...mixins) {
  return target => mixins.reduce(applyMixin, target);
}

export default applyMixinBuilder;
```

**Comment by goncalvesjoao** [comment]
Great!

**Pull request merged**
